version: '3.8'

services:
  orchestrator:
    build: .
    command: go run ./cmd/orchestrator
    env_file: .env
    ports:
      - "${PUBLIC_PORT}:${PUBLIC_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - data:/app/data

  agent:
    build: .
    command: go run ./cmd/agent
    env_file: .env
    depends_on:
      - orchestrator

volumes:
  data:
