// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_AddOperation Operation = 0
	Operation_SubOperation Operation = 1
	Operation_MulOperation Operation = 2
	Operation_DivOperation Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "AddOperation",
		1: "SubOperation",
		2: "MulOperation",
		3: "DivOperation",
	}
	Operation_value = map[string]int32{
		"AddOperation": 0,
		"SubOperation": 1,
		"MulOperation": 2,
		"DivOperation": 3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_task_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_pkg_proto_task_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          float64                `protobuf:"fixed64,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float64                `protobuf:"fixed64,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     Operation              `protobuf:"varint,4,opt,name=operation,proto3,enum=orchestrator.Operation" json:"operation,omitempty"`
	OperationTime int32                  `protobuf:"varint,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetArg1() float64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_AddOperation
}

func (x *Task) GetOperationTime() int32 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_pkg_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_pkg_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TaskRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_pkg_proto_task_proto protoreflect.FileDescriptor

const file_pkg_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/task.proto\x12\forchestrator\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\x01R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\x01R\x04arg2\x125\n" +
	"\toperation\x18\x04 \x01(\x0e2\x17.orchestrator.OperationR\toperation\x12%\n" +
	"\x0eoperation_time\x18\x05 \x01(\x05R\roperationTime\"6\n" +
	"\fTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.orchestrator.TaskR\x04task\"V\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode*S\n" +
	"\tOperation\x12\x10\n" +
	"\fAddOperation\x10\x00\x12\x10\n" +
	"\fSubOperation\x10\x01\x12\x10\n" +
	"\fMulOperation\x10\x02\x12\x10\n" +
	"\fDivOperation\x10\x032\x8d\x01\n" +
	"\vTaskService\x12=\n" +
	"\aGetTask\x12\x16.google.protobuf.Empty\x1a\x1a.orchestrator.TaskResponse\x12?\n" +
	"\n" +
	"SubmitTask\x12\x19.orchestrator.TaskRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/MaxGolubev19/GoCalculator/pkg/protob\x06proto3"

var (
	file_pkg_proto_task_proto_rawDescOnce sync.Once
	file_pkg_proto_task_proto_rawDescData []byte
)

func file_pkg_proto_task_proto_rawDescGZIP() []byte {
	file_pkg_proto_task_proto_rawDescOnce.Do(func() {
		file_pkg_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_task_proto_rawDesc), len(file_pkg_proto_task_proto_rawDesc)))
	})
	return file_pkg_proto_task_proto_rawDescData
}

var file_pkg_proto_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_task_proto_goTypes = []any{
	(Operation)(0),        // 0: orchestrator.Operation
	(*Task)(nil),          // 1: orchestrator.Task
	(*TaskResponse)(nil),  // 2: orchestrator.TaskResponse
	(*TaskRequest)(nil),   // 3: orchestrator.TaskRequest
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_pkg_proto_task_proto_depIdxs = []int32{
	0, // 0: orchestrator.Task.operation:type_name -> orchestrator.Operation
	1, // 1: orchestrator.TaskResponse.task:type_name -> orchestrator.Task
	4, // 2: orchestrator.TaskService.GetTask:input_type -> google.protobuf.Empty
	3, // 3: orchestrator.TaskService.SubmitTask:input_type -> orchestrator.TaskRequest
	2, // 4: orchestrator.TaskService.GetTask:output_type -> orchestrator.TaskResponse
	4, // 5: orchestrator.TaskService.SubmitTask:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_task_proto_init() }
func file_pkg_proto_task_proto_init() {
	if File_pkg_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_task_proto_rawDesc), len(file_pkg_proto_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_task_proto_goTypes,
		DependencyIndexes: file_pkg_proto_task_proto_depIdxs,
		EnumInfos:         file_pkg_proto_task_proto_enumTypes,
		MessageInfos:      file_pkg_proto_task_proto_msgTypes,
	}.Build()
	File_pkg_proto_task_proto = out.File
	file_pkg_proto_task_proto_goTypes = nil
	file_pkg_proto_task_proto_depIdxs = nil
}
